version: "3.9"

services:
  user-service-db:
    image: postgres:17
    container_name: user-service-db
    env_file:
      - ./backend/user-service/.env
    ports:
      - "5434:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  restaurant-service-db:
    image: postgres:17
    container_name: restaurant-service-db
    env_file:
      - ./backend/restaurant-service/.env
    ports:
      - "5435:5432"
    volumes:
      - restaurant_pgdata:/var/lib/postgresql/data
  order-service-db:
    image: postgres:17
    container_name: order-service-db
    env_file:
      - ./backend/order-service/.env
    ports:
      - "5436:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-images
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    env_file:
      - ./backend/user-service/.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - user-service-db
    ports:
      - "8081:8081"
  restaurant-service:
    build:
      context: ./backend/restaurant-service
      dockerfile: Dockerfile
    image: restaurant-service
    container_name: restaurant-service
    env_file:
      - ./backend/restaurant-service/.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - restaurant-service-db
    ports:
      - "9090:9090"
  order-service:
    build:
      context: ./backend/order-service
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service
    env_file:
      - ./backend/order-service/.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - order-service-db
    ports:
      - "8080:8080"

volumes:
  user_pgdata:
  restaurant_pgdata:
  order_pgdata:
  minio_data:
